spring:
  datasource:
    password: letmein
    url: jdbc:mysql://localhost:3306/financedb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show_sql: true
    security:
      user:
        name: admin
        password: letmein
logging:
  level:
    org:
      springframework:
        security: DEBUG
        com:
          fasterxml:
            jackson: DEBUG
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestMappingHandlerMapping=TRACE: